version: '2.15.1'

services:
  serverjar:
    build:
      context: .
      target: server

    expose:
      - 8080
    volumes:
      - h2data:/data/h2db

  clientjar:
    environment:
      - DISPLAY=host.docker.internal:0.0
    build:
      context: .
      target: client

    depends_on:
      - serverjar
volumes:
  h2data:
    driver: local